- name: demo on simple playbook
  hosts: all
  tasks:
    - name: Task1
      ansible.builtin.debug:
        msg: 'Hello from Playbook paly'
    - name: Task2
      ansible.builtin.debug:
        msg: 'Hello from Playbook Task2'