- name: tag demo on tasks
  hosts: localhost
  tasks:
    - name: Catalogue
      debug:
        msg: Hello from Catalogue
      tags: catalogue
    - name:  Frontend
      debug:
        msg: Hello from Frontend
      tags: frontend
    - name: Common
      debug:
        msg: Hello from Common